# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ devle ]
  pull_request:
    branches: [ devle ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
<<<<<<< 8e131bab928cc5b268cc93ed8ee3701c30857092
        # node-version: [10.x, 12.x, 14.x, 15.x] # 15.x taobao 有问题
        node-version: [10.x, 12.x, 14.x]
=======
        node-version: [10.x, 12.x, 14.x, 15.x]
>>>>>>> Create node.js.yml
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
